### ISSUE TITLE
ImportError: No module named 'jsocket_base'

### ISSUE THREAD

**Issue by stroobandt** [chris-piekarski/python-json-socket#4]
Dear Chris.

I am trying out your example multithreaded server on Ubuntu 16.04 after installing it with:

    $ sudo pip3 install jsocket

Before doing so, I made sure that `pip3` is up to date.
Nonetheless, running the server script results in the following error:
```
    import jsocket
  File "/usr/local/lib/python3.5/dist-packages/jsocket/__init__.py", line 74, in <module>
    from jsocket_base import *
ImportError: No module named 'jsocket_base'
```

**Comment by tudorp** [comment]
Dear Chris,

I can also confirm an equivalent issue to the one previous reported by @stroobandt. 
The difference is that I get it while running the example on Windows 10 x64 with python 3.6.1 in PyCharm after automatically importing the jsocket module
`Traceback (most recent call last):
  File "jsocktest.py", line 2, in <module>
    import jsocket
  File "Python\lib\site-packages\jsocket\__init__.py", line 74, in <module>
    from jsocket_base import *
ModuleNotFoundError: No module named 'jsocket_base'`

**Comment by chris-piekarski** [comment]
Hi @stroobandt and @tudorp 
I apologize for missing the notification for this issue for so long
I am sure you have long since moved on but nonetheless I will put together a python 3 branch and share new packages for for pip3
Thanks, Chris

**Comment by chris-piekarski** [comment]
branch python_3_port
will push out new pip3 package and update in dup issue #5
